### ISSUE TITLE
Comprobar todos los tipos que se pueda

### ISSUE THREAD

**Issue by JJ** [cr13/RecetaCoctel#35]
¿Dificultad qué tipo es? ¿e Ingredientes? ¿Debe ser una lista? Sólo se comprueban parte de los argumentos.

https://github.com/cr13/RecetaCoctel/blob/7560e6f22ce665800073eb2aed40659f8f17d7fd/src/Receta.js#L22

Deben diseñarse también los errores de forma que sean diferentes para diferentes tipos de problemas. No pueden lanzar una excepción sin determinación, porque entonces no se pude propagar al usuadio de forma correcta.

**Comment by cr13** [comment]
Se ha cambiado el tipo dificultad de string a una enumeracion, definiendo 3 tipos (Facil, medio y dificil), se ha realizado un chequeo de que se reciba uno de estos 3 tipos. 
Además se ha controlado que la lista de ingredientes recibida lo que contenga sean ingredientes.
Por consecuencia de dichos controles se han modificado los test correspondientes.
